-- Angewendet am 2026-10-10 auf course_exercises (31 Zeilen, Bedingung: Lösung unverändert). Undo: Spalten alt und neu im SET/WHERE tauschen.
update course_exercises c set solution = v.neu from (values
(215,$q$hibb (Sg.) / hibbu (Pl.)$q$,$q$7ibb (Sg.) / 7ibbu (Pl.)$q$),
(541,$q$tahti, tahtik, tahtu, tahtha; tahtna, tahtkum, tahthum$q$,$q$ta7ti, ta7tik, ta7tu, ta7tha; ta7tna, ta7tkum, ta7thum$q$),
(557,$q$ena waqif bahdahum. — Ich stehe neben ihnen.$q$,$q$ena waqif ba7dahum. — Ich stehe neben ihnen.$q$),
(571,$q$il-farmasi bi-znabu. — Die Apotheke ist neben ihm.$q$,$q$il-farmasi bi-jnabu. — Die Apotheke ist neben ihm.$q$),
(654,$q$bahdatna famma tbib.$q$,$q$ba7datna famma tbib.$q$),
(655,$q$bahdatkum famma 7anut.$q$,$q$ba7datkum famma 7anut.$q$),
(656,$q$famma-shi tbib bahdatkum?$q$,$q$famma-shi tbib ba7datkum?$q$),
(763,$q$ih, nhibbuha. / la, ma-nhibbuha-sh. — Möchtet ihr eine Wasserpfeife?$q$,$q$ih, n7ibbuha. / la, ma-n7ibbuha-sh. — Möchtet ihr eine Wasserpfeife?$q$),
(799,$q$nihibbu nishthu. — Ich und meine Schwester tanzen gern. Neg: ma-nihibbu-sh nishthu.$q$,$q$ni7ibbu nishthu. — Ich und meine Schwester tanzen gern. Neg: ma-ni7ibbu-sh nishthu.$q$),
(804,$q$nihibbu ninjhu. — Wir möchten Erfolg haben. Neg: ma-nihibbu-sh ninjhu.$q$,$q$ni7ibbu ninjhu. — Wir möchten Erfolg haben. Neg: ma-ni7ibbu-sh ninjhu.$q$),
(1058,$q$ukhti ish-shghira far7ana, ama khuya il-kbir 7zin.$q$,$q$ukhti is-sghira far7ana, ama khuya il-kbir 7zin.$q$),
(1273,$q$ih, tamma nas yahkiu bil-fransawiya hna. "Ja, es gibt Leute, die hier Französisch sprechen."$q$,$q$ih, tamma nas ya7kiu bil-fransawiya hna. "Ja, es gibt Leute, die hier Französisch sprechen."$q$),
(1380,$q$dqiqa l-uruppa (fi-t-talifun) ghalya barsha.$q$,$q$dqiqa l-urubba (fi-t-talifun) ghalya barsha.$q$),
(1387,$q$khuya ish-shghir yhibb yakul hluwiyat.$q$,$q$khuya is-sghir yhibb yakul 7luwiyat.$q$),
(1404,$q$shnuwwa hwalu?$q$,$q$shnuwwa 7walu?$q$),
(1405,$q$shnuwwa hwalha?$q$,$q$shnuwwa 7walha?$q$),
(1513,$q$fra7, frahit, fraht, fraht; Pl. frahu, frahu, frahtu, frahna.$q$,$q$fra7, fra7it, fra7t, fra7t; Pl. fra7u, fra7u, fra7tu, fra7na.$q$),
(1520,$q$7sib, hisbit, 7sibt, 7sibt; Pl. hisbu, hisbu, hsibtu, hsibna.$q$,$q$7sib, 7isbit, 7sibt, 7sibt; Pl. 7isbu, 7isbu, 7sibtu, 7sibna.$q$),
(1530,$q$khrajt il-barra ki smast 7iss.$q$,$q$khrajt il-barra ki sma3t 7iss.$q$),
(1670,$q$zitt q3adt bahdahum shwayya.$q$,$q$zitt q3adt ba7dahum shwayya.$q$),
(1815,$q$7fad, hfadit, hfadt, hfadt; Pl. hfadu, hfadu, hfadtu, hfadna.$q$,$q$7fad, 7fadit, 7fadt, 7fadt; Pl. 7fadu, 7fadu, 7fadtu, 7fadna.$q$),
(1818,$q$shta7, shtahit, shtaht, shtaht; Pl. shtahu, shtahu, shtahtu, shtahna.$q$,$q$shta7, shta7it, shta7t, shta7t; Pl. shta7u, shta7u, shta7tu, shta7na.$q$),
(1827,$q$7lif, hilfit, hlift, hlift; Pl. hilfu, hilfu, hliftu, hlifna.$q$,$q$7lif, 7ilfit, 7lift, 7lift; Pl. 7ilfu, 7ilfu, 7liftu, 7lifna.$q$),
(1838,$q$7ass, 7assit, 7assit, 7assit; Pl. hassu, hassu, hassitu, 7assina.$q$,$q$7ass, 7assit, 7assit, 7assit; Pl. 7assu, 7assu, 7assitu, 7assina.$q$),
(2023,$q$xallihum yahbtu. (Lass sie aussteigen/runtergehen! -- statt: einsteigen/hochgehen.)$q$,$q$xallihum ya7btu. (Lass sie aussteigen/runtergehen! -- statt: einsteigen/hochgehen.)$q$),
(2051,$q$shnuwwa hwalhum?$q$,$q$shnuwwa 7walhum?$q$),
(2052,$q$shnuwwa hwalha?$q$,$q$shnuwwa 7walha?$q$),
(2056,$q$hetha sahibhum.$q$,$q$hetha sa7ibhum.$q$),
(2072,$q$hethi 7mat sa7bi. hethi hmatu. — Wessen Schwiegermutter ist das? (mein Freund) Das ist die Schwiegermutter meines Freundes. Das ist seine.$q$,$q$hethi 7mat sa7bi. hethi 7matu. — Wessen Schwiegermutter ist das? (mein Freund) Das ist die Schwiegermutter meines Freundes. Das ist seine.$q$),
(2143,$q$khalluna fi-halna!$q$,$q$khalluna fi-7alna!$q$),
(2150,$q$ma-najjamt-sh nilqa miftahi fi-7atta blasa.$q$,$q$ma-najjamt-sh nilqa mifta7i fi-7atta blasa.$q$)
) as v(id,alt,neu) where c.id = v.id and c.solution = v.alt returning c.id;
